In [8]:
import numpy as np

# Initialize a 2x2 array with uninitialized values (empty)
array = np.empty((2, 2), dtype=object)

print(array)


[[None None]
 [None None]]


In [6]:
import numpy as np

# Initialize a 4x2 array with all ones
array = np.ones((4, 2))

print(array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
import numpy as np

# Create a 3x3 array of type float, filled with the value 7
array = np.full((3, 3), 7.0)

print(array)


[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [9]:
import numpy as np

# Example array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a new array of zeros with the same shape and type as the original array
zeros_array = np.zeros_like(array)

print(zeros_array)


[[0 0 0]
 [0 0 0]]


In [10]:
import numpy as np

# Example array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a new array of ones with the same shape and type as the original array
ones_array = np.ones_like(array)

print(ones_array)


[[1 1 1]
 [1 1 1]]


In [11]:
import numpy as np

# Existing list
new_list = [1, 2, 3, 4]

# Convert the list to a NumPy array
array = np.array(new_list)

print(array)


[1 2 3 4]


problem 2


In [12]:

import numpy as np

# Create an array with values ranging from 10 to 49
array = np.arange(10, 50)

print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
import numpy as np

# Create an array with values from 0 to 8
array = np.arange(9)

# Reshape the array into a 3x3 matrix
matrix = array.reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
import numpy as np

# Create a random array of size 30 with values between 0 and 1
random_array = np.random.random(30)

# Calculate the mean of the array
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the array:", mean_value)


Random Array: [0.73914691 0.74528419 0.87149565 0.93271094 0.12101008 0.44040788
 0.2377366  0.95495621 0.96028503 0.33480583 0.07514657 0.89421134
 0.9777727  0.11021352 0.3183583  0.1697635  0.57122737 0.35429011
 0.27068494 0.79094992 0.97947971 0.6782995  0.57933887 0.65350206
 0.47645548 0.14944194 0.09339331 0.62907462 0.65498438 0.80470636]
Mean of the array: 0.5523044604656696


In [16]:
import numpy as np

# Create a 10x10 array with random values between 0 and 1
random_array = np.random.random((10, 10))

# Find the minimum and maximum values in the array
min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 Array:\n", random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


Random 10x10 Array:
 [[0.53833419 0.31187523 0.97953082 0.35448948 0.06305538 0.35847127
  0.58854726 0.39083273 0.1694895  0.99221463]
 [0.54420533 0.94271711 0.63187952 0.75771508 0.44141238 0.49728828
  0.74632189 0.81239043 0.01559754 0.19063572]
 [0.62330059 0.20964196 0.55882563 0.81955925 0.81496453 0.6342935
  0.10742293 0.99839935 0.29570116 0.36882894]
 [0.38793135 0.46630844 0.50002889 0.12748553 0.58167418 0.95835211
  0.00226933 0.79677127 0.04982588 0.2624684 ]
 [0.82919191 0.40701308 0.81562026 0.90450863 0.20926496 0.51059884
  0.51207246 0.98193627 0.86824885 0.00598857]
 [0.85309798 0.13851353 0.46734763 0.2925275  0.1921548  0.35558964
  0.5397659  0.368393   0.60517852 0.66665517]
 [0.65167257 0.71007507 0.60294103 0.85486927 0.12463823 0.23244901
  0.31936108 0.82501552 0.83772355 0.00442448]
 [0.04964243 0.20041077 0.47746524 0.08641554 0.43913478 0.8559746
  0.06650146 0.99166664 0.02292476 0.50565085]
 [0.61836556 0.28413963 0.2371949  0.22035498 0.28916521 0.23

In [17]:
import numpy as np

# Create a zero array of size 10
array = np.zeros(10)

# Replace the 5th element (index 4) with 1
array[4] = 1

print(array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
import numpy as np

# Define the array
arr = np.array([1, 2, 0, 0, 4, 0])

# Reverse the array using slicing
reversed_arr = arr[::-1]

print(reversed_arr)


[0 4 0 0 2 1]


In [19]:
import numpy as np

# Define the size of the array (e.g., 5x5)
size = 5

# Create a 2D array filled with zeros
array = np.zeros((size, size))

# Set the border elements to 1
array[0, :] = 1  # Top row
array[-1, :] = 1  # Bottom row
array[:, 0] = 1  # Left column
array[:, -1] = 1  # Right column

print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8))

# Fill the checkerboard pattern
matrix[1::2, ::2] = 1  # Fill alternating rows and columns with 1
matrix[::2, 1::2] = 1  # Fill the other alternating rows and columns with 1

print(matrix)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


problem 3


In [22]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])



add_result = x + y
print("Addition of x and y:\n", add_result)



Addition of x and y:
 [[ 6  8]
 [10 13]]


In [23]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


subtract_result = x - y
print("Subtraction of x and y:\n", subtract_result)


Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [24]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

multiply_result = x * 2
print("Multiplication of x by 2:\n", multiply_result)


Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]


In [25]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

square_result = np.square(x)
print("Square of each element in x:\n", square_result)


Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [26]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_v_w = np.dot(v, w)
print("Dot product of v and w:", dot_v_w)


Dot product of v and w: 219


In [27]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_x_v = np.dot(x, v)
print("Dot product of x and v:", dot_x_v)


Dot product of x and v: [29 77]


In [28]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_x_y = np.dot(x, y)
print("Dot product of x and y:\n", dot_x_y)


Dot product of x and y:
 [[19 22]
 [50 58]]


In [29]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_x_y = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_x_y)


Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [32]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_v_w = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("Concatenate v and w along columns:\n", concat_v_w)

try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("Concatenate x and v along rows:\n", concat_x_v)
except Exception as e:
    print("Error:", e)



Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


PROBLEM 4

In [33]:
import numpy as np

# Define the matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse
result_A_A_inv = np.dot(A, A_inv)

# Identity matrix (2x2)
identity_matrix = np.eye(2)

print("A * A^-1 = \n", result_A_A_inv)
print("Identity Matrix (I): \n", identity_matrix)

# Check if the result is approximately the identity matrix
is_identity = np.allclose(result_A_A_inv, identity_matrix)
print("Is A * A^-1 equal to I? ", is_identity)


# Calculate AB
AB = np.dot(A, B)

# Calculate BA
BA = np.dot(B, A)

print("AB = \n", AB)
print("BA = \n", BA)

# Check if AB is equal to BA
is_equal = np.allclose(AB, BA)
print("Is AB equal to BA? ", is_equal)


# Calculate (AB)^T
AB_T = (np.dot(A, B)).T

# Calculate B^T * A^T
B_T_A_T = np.dot(B.T, A.T)

print("Transpose of AB (AB)^T = \n", AB_T)
print("B^T * A^T = \n", B_T_A_T)

# Check if (AB)^T is equal to B^T * A^T
is_equal_transpose = np.allclose(AB_T, B_T_A_T)
print("Is (AB)^T equal to B^T * A^T? ", is_equal_transpose)




A * A^-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix (I): 
 [[1. 0.]
 [0. 1.]]
Is A * A^-1 equal to I?  True
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Is AB equal to BA?  False
Transpose of AB (AB)^T = 
 [[23 51]
 [13 29]]
B^T * A^T = 
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T?  True


In [34]:
import numpy as np

# Define the coefficient matrix A and the constant matrix B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the formula X = A_inv * B
X = np.dot(A_inv, B)

print("Solution for [x, y, z]:", X)


Solution for [x, y, z]: [ 2.  1. -2.]


In [35]:
import numpy as np

# Define the coefficient matrix A and the constant matrix B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Use np.linalg.inv() to calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the formula X = A_inv * B
X = np.dot(A_inv, B)

print("Solution for [x, y, z]:", X)


Solution for [x, y, z]: [ 2.  1. -2.]
